### ISSUE TITLE
Navigator bug

### ISSUE THREAD

**Issue by LoafofBread11** [cjr0265/csce3444-al-dente#1]
The navigator currently allows for using the swipe gesture on IOS to return to the login screen after already logging in
![IMG_1911](https://user-images.githubusercontent.com/89869613/139922564-a27ffeb5-c363-4fcb-94fd-140b407e27d6.PNG)

**Comment by The-Official-Horus** [comment]
Edited lines in App.js to prevent swipe back features for the time being. Will be modified later on to allow where needed.
